# Generated by Django 3.2.12 on 2023-06-16 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carboncredit',
            old_name='credit_sold',
            new_name='credits_remaining',
        ),
        migrations.RenameField(
            model_name='carboncreditpurchase',
            old_name='buyer',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='carboncredit',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='carboncredit',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='carboncredit',
            name='sold_to',
        ),
        migrations.CreateModel(
            name='CarbonCreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credit_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.carboncredit')),
            ],
        ),
    ]
