# Generated by Django 3.2.12 on 2023-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0002_auto_20230616_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='original_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carboncreditpurchase',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carboncreditsale',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
