# Generated by Django 4.2.1 on 2023-05-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_purchase_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='date_of_purchase',
        ),
    ]
